import { NextResponse } from "next/server";
import { requireUser } from "@/lib/auth/session";
import { getMongoDatabase } from "@/lib/mongodb/client";
import { getCollections } from "@/lib/mongodb/collections";
import { rangeStart } from "@/lib/statistics/config";
import { donationScope } from "@/lib/statistics/scope";
export async function GET(request: Request) { try { const auth = await requireUser(); if ("error" in auth) return NextResponse.json({ error: auth.error }, { status: auth.status }); const db = await getMongoDatabase(); if (!db) return NextResponse.json({ error: "MongoDB is not configured." }, { status: 503 }); const collections = getCollections(db); const start = rangeStart(new URL(request.url).searchParams.get("range")); const [supply, demand, storage] = await Promise.all([
  collections.donations.aggregate<{ category: string; pounds: number; donations: number }>([{ $match: { ...donationScope(auth.user), ...(start ? { createdAt: { $gte: start } } : {}) } }, { $group: { _id: "$foodCategory", pounds: { $sum: "$quantityLbs" }, donations: { $sum: 1 } } }, { $project: { _id: 0, category: "$_id", pounds: 1, donations: 1 } }, { $sort: { pounds: -1 } }]).toArray(),
  collections.organizationNeeds.aggregate<{ category: string; poundsNeeded: number }>([{ $match: { active: true, ...(auth.user.role === "food_org" ? { organizationId: auth.user.organizationId || "__none__" } : {}) } }, { $group: { _id: "$foodCategory", poundsNeeded: { $sum: { $max: [{ $subtract: ["$desiredQuantityLbs", "$currentQuantityLbs"] }, 0] } } } }, { $project: { _id: 0, category: "$_id", poundsNeeded: 1 } }, { $sort: { poundsNeeded: -1 } }]).toArray(),
  collections.donations.aggregate<{ storageType: string; count: number }>([{ $match: { ...donationScope(auth.user), ...(start ? { createdAt: { $gte: start } } : {}) } }, { $group: { _id: "$storageType", count: { $sum: 1 } } }, { $project: { _id: 0, storageType: "$_id", count: 1 } }]).toArray(),
]); const categories = [...new Set([...supply.map((item) => item.category), ...demand.map((item) => item.category)])].map((category) => ({ category, suppliedLbs: supply.find((item) => item.category === category)?.pounds || 0, neededLbs: demand.find((item) => item.category === category)?.poundsNeeded || 0 })); return NextResponse.json({ supply, demand, storage, categories }); } catch (error) { console.error(error); return NextResponse.json({ error: "Unable to calculate category insights." }, { status: 500 }); } }
